language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
    - ~/.npm
git:
  depth: 3
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      name: 'Automation Tests'
      script: yarn test
after_script:
  - yarn clean
